[versions]
coreTesting = "2.2.0"
glide = "4.16.0"
lottie = "6.6.7"
minSdk = "28"
shimmer = "0.5.0"
targetSdk = "36"
versionCode = "3"
versionName = "1.0.2"
agp = "8.9.3"
kotlin = "2.2.0"
coreKtx = "1.15.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
okhttp = "5.1.0"
retrofit = "2.9.0"
kotlinx-serialization-json = "1.8.1"
retrofit2-kotlinx-serialization-converter = "1.0.0"
kotlinx-coroutines-android = "1.3.9"
kotlinx-coroutines-test = "1.7.3"
junit-jupiter = "5.12.0"
kotest-runner-junit5 = "5.9.1"
android-junit5 = "1.12.0.0"
ktlint = "13.0.0"
fragment-ktx = "1.8.8"
google-services = "4.4.3"
firebase-bom = "34.0.0"
kakaoV2User = "2.21.4"
workManager = "2.10.3"
healthConnect = "1.2.0-alpha01"
mockk = "1.14.0"
assertj-core = "3.27.3"
timber = "5.0.1"
firebase-crashlytics = "3.0.5"
androidsvg = "1.4"
kapt = "2.2.0"
github-triplet-play = "3.12.1"

[libraries]
# AndroidX 및 UI
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }

# 네트워크 및 직렬화
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-kotlinx-serialization-converter" }

# 코루틴
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }

# 테스트
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest-runner-junit5" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj-core" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# 이미지 로딩
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
androidsvg = { module = "com.caverock:androidsvg", version.ref = "androidsvg" }

# 로그인
kakao-v2-user = { module = "com.kakao.sdk:v2-user", version.ref = "kakaoV2User" }

# 파이어베이스
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ndk" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

# 로깅
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# 헬스 커넥트 연결
androidx-health-connect = { module = "androidx.health.connect:connect-client", version.ref = "healthConnect" }

# 워크매니저
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }

# 스켈레톤
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlin-parcelize = { id = "kotlin-parcelize" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
github-triplet-play = {id = "com.github.triplet.play", version.ref = "github-triplet-play"}
