spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver

  sql:
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/common, classpath:db/migration/h2
    validate-on-migrate: true
    clean-disabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  logging:
    mask-auth: false
