name: Android CI

on:
  pull_request:
    branches: [ "develop", "develop-an" ]
    paths:
      - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./android

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: set up gradle cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          android/.gradle
        key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-cache-${{ runner.os }}-
    
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: set up local.properties
      env:
        RELEASE_BASE_URL:  ${{ secrets.RELEASE_BASE_URL }}
        DEBUG_BASE_URL:    ${{ secrets.DEBUG_BASE_URL }}
        KEY_KAKAO:         ${{ secrets.DEBUG_BASE_URL }}
      run: |
        echo "release.base.url=${RELEASE_BASE_URL}" >> ./local.properties
        echo "debug.base.url=${DEBUG_BASE_URL}"     >> ./local.properties
        echo "key.kakao=${KEY_KAKAO}"               >> ./local.properties

    - name: set up google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      run: |
        echo "$GOOGLE_SERVICES" | base64 --decode > app/google-services.json

    - name: grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: build with Gradle
      run: ./gradlew build --build-cache --parallel --configuration-cache
      
    - name: Check ktlint format
      run: ./gradlew ktlintCheck
      
    - name: Perform Gradle Test
      run: ./gradlew test --build-cache --parallel
